### ISSUE TITLE
[依頼]】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by takuya0323** [takuya0323/protospace-39168#1]
＃URL
https://protospace-39168.onrender.com/

よろしくお願いいたします。
本田卓也

**Comment by mo1015** [comment]
@takuya0323 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **削除が完了すると、トップページへ遷移すること**
削除ボタンを押してもトップページへ遷移しません。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
